name: YouTube Automation

on:
  workflow_dispatch:   # manual run button
  schedule:
    - cron: '0 9,14,20 * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install FFmpeg
        run: sudo apt update && sudo apt install ffmpeg -y

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Bot
        run: python main.py
